### ISSUE TITLE
Unable to import the module into a python script "Segmentation Fault".

### ISSUE THREAD

**Issue by anasshaddad** [zippy84/vtkbool#56]
First of all, I want to thank you for the work you are doing. I was able to compile the package but I can't import it into my python script, it gives me a segmentation error as shown in the figure below
![image (2)](https://user-images.githubusercontent.com/61286004/182389039-efad5196-8af8-48e1-b1da-c83011f14fde.png)
.

**Comment by CalumFreeman** [comment]
This is also a problem for me, the segfault occurs when this snippet is called:
```
PyTypeObject *pytype = PyVTKClass_Add(
    &PyvtkPolyDataBooleanFilter_Type, PyvtkPolyDataBooleanFilter_Methods,
    "vtkPolyDataBooleanFilter",
 &PyvtkPolyDataBooleanFilter_StaticNew);
```
It's called from `vtkbool/build/CMakeFiles/vtkBoolPython/vtkPolyDataBooleanFilterPython.cxx`, which is a file generated as part of cmake. I think it's generated from this macro (but I'm not sure since I don't know how vtk builds things):
https://github.com/zippy84/vtkbool/blob/eed1106bec1e91dc0ed4a86060bcad3a220b292d/vtkPolyDataBooleanFilter.cxx#L54

The C++ version of the module appears to work fine for me, I'm using that for now, thanks for building this!

**Comment by zippy84** [comment]
@anasshaddad Please say something about your environment.

**Comment by zippy84** [comment]
@CalumFreeman What about you?

**Comment by zippy84** [comment]
I'm closing this as no additional information was added.
