### ISSUE TITLE
Difference boolean operation (e.g. A-B) leads to crash

### ISSUE THREAD

**Issue by mauigna06** [zippy84/vtkbool#72]
Hi @zippy84 

Thanks for the amazing software

I can replicate crashes with the file below

[vtk_bool_difference_A-B_operation_bug.zip](https://github.com/zippy84/vtkbool/files/13877924/vtk_bool_difference_A-B_operation_bug.zip)

Hope you can help

PS: I worked around it by adding some filters to the [pipeline](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/commit/a8eec0b588d59907c6440c098c5da2f033ec4076#) that creates the cylinders

**Comment by zippy84** [comment]
Respectively with SetOperModeToDifference:

![grafik](https://github.com/zippy84/vtkbool/assets/373343/9e0e42eb-fde3-406a-9a16-f8c6400e35a7)

**Comment by mauigna06** [comment]
> do you use the newest version of my lib?

I don't know how to check, I think the files of vtkbool are inside this folder:
https://github.com/PerkLab/SlicerSandbox/tree/master/CombineModels/Logic

It appears they are a few years old

**Comment by zippy84** [comment]
Yes, the files there are really old. You should upgrade to version 3.0. The new version is much better!! :smiley:

**Comment by BigBrotherHui** [comment]
> Yes, the files there are really old. You should upgrade to version 3.0. The new version is much better!! 😃

where is the newest version of vtkbool?the slicersandbox have't update the login 3 years age

**Comment by BigBrotherHui** [comment]
> Yes, the files there are really old. You should upgrade to version 3.0. The new version is much better!! 😃

where is the newest version of vtkbool?the slicersandbox have't update the logic 3 years age

**Comment by lassoan** [comment]
Thank you, we've updated vtkbool in the Slicer extension now. The current vtkbool version is indeed much cleaner, properly wrapped, and available as a VTK module, so in the future we'll not have to vendorize it anymore.

The only changes I had to make in vtkbool to allow it to build on Windows were:
- [Add `#define _USE_MATH_DEFINES` to Utilities.cxx](https://github.com/PerkLab/SlicerSandbox/blob/239e535f9931359e315f52ca93800cf0343d8344/CombineModels/Logic/Utilities.cxx#L17) (without that build failed due to `M_PI` symbol was not found).
- [Exclude the `_Pair` class from wrapping](https://github.com/PerkLab/SlicerSandbox/blob/239e535f9931359e315f52ca93800cf0343d8344/CombineModels/Logic/Utilities.h#L86-L105). Maybe it was due to something not being optimal in our CMake files, as Utilities.cxx/.h should not have been even considered by the wrapper; but since Utilities.h was included in Python-wrapped header files, I did not see any easy way around it. For a nice and clean interface, it woud be nice if all the private implementation details (such as `StripPt`, `StripPtR`, `PStrips`, etc. classes, and `#include "Utilities.h"`) could be removed from vtkPolyDataContactFilter.h and vtkPolyDataBooleanFilter.h header files (and would be included only in the .cxx files).

**Comment by zippy84** [comment]
> * [Add `#define _USE_MATH_DEFINES` to Utilities.cxx](https://github.com/PerkLab/SlicerSandbox/blob/239e535f9931359e315f52ca93800cf0343d8344/CombineModels/Logic/Utilities.cxx#L17) (without that build failed due to `M_PI` symbol was not found).

This is defined by my CMakeLists.txt :smile:
